name: Run Testcases
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: cd client
      - run: npm install
      - run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
